# Payu configuration

# If submitting to a different project to your default, uncomment line below
# and change project code as appropriate; also set shortpath below
# project: <project>
# Force payu to always find, and save, files in this scratch project directory
# shortpath: /scratch/<project>

modules:
  use:
    - /g/data/vk83/prerelease/modules
  load:
    - access-om3/pr140-7

queue: normalsr
ncpus: 312
walltime: 12:00:00
jobname: anu-tub

model: mom6
exe: mom6-solo
input:
  # Inputs can be created using the notebook in ./input
  - ./input/topog.nc
  - ./input/forcing.nc
  - ./input/sst.nc

runlog: false
metadata:
  enable: false
manifest:
  reproduce:
    exe: true

collate: false

qsub_flags: -W umask=027

restart_freq: 1

