format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/ol01/amh157/mom6/archive/anu-tub/restart590/MOM.res.nc
  hashes:
    binhash: 37f957b3238a58fe6addaf711eb19352
    md5: 0da6149a753776396d33cee51d408424
work/INPUT/ocean_solo.res:
  fullpath: /scratch/ol01/amh157/mom6/archive/anu-tub/restart590/ocean_solo.res
  hashes:
    binhash: 06b82cbae42533c77d2159d4764db1f4
    md5: a110e02b6429915cf1d2fb5beb50977b
