format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/ol01/amh157/mom6/archive/anu-tub-adapt-anu-tub-adapt-n8-cb2a72cd/restart012/MOM.res.nc
  hashes:
    binhash: a15f5c4a049ad71e76ce67f42a2fd9f8
    md5: fd5d13b3afd9de65c2bb156e3c7c9ce2
work/INPUT/ocean_solo.res:
  fullpath: /scratch/ol01/amh157/mom6/archive/anu-tub-adapt-anu-tub-adapt-n8-cb2a72cd/restart012/ocean_solo.res
  hashes:
    binhash: f4058599269f7952262a785d02640ab5
    md5: d628e275ee8f8980a9c34201201ebcec
