ncpus: 240
walltime: 03:00:00
jobname: tub-hyc
project: ol01
queue: normal

model: mom6
exe: /g/data/x77/ahg157/exes/MOM6/AG-07f0a144
input: ../../input

storage:
  gdata:
    - ol01
    - x77

collate: False

mpi:
    module: openmpi/4.1.2

qsub_flags: -W umask=027

