format: yamanifest
version: 1.0
---
work/INPUT/forcing.nc:
  fullpath: /g/data/x77/amh157/mom6-idealised-configs/input/forcing.nc
  hashes:
    binhash: 277cb99c9f060d033ef037337e71d850
    md5: 9d8323ed9d4dfa698bfc84bad18ae696
work/INPUT/mom6-anu-tub-driver.ipynb:
  fullpath: /g/data/x77/amh157/mom6-idealised-configs/input/mom6-anu-tub-driver.ipynb
  hashes:
    binhash: 814f9443d7117b4d82185dc8a5fbbf3a
    md5: c53d85a94c7e0bdb4d5172ed9c1bba7c
work/INPUT/sst.nc:
  fullpath: /g/data/x77/amh157/mom6-idealised-configs/input/sst.nc
  hashes:
    binhash: 35f59921f6d264b94b5b28c16d28c9fa
    md5: 0a187993c300c9b48bb07974519a5b74
work/INPUT/topog.nc:
  fullpath: /g/data/x77/amh157/mom6-idealised-configs/input/topog.nc
  hashes:
    binhash: 4c83de7aa477d4d9398a1b14f2b35d6a
    md5: 226cf401ebd640b69a57cbb3fb0c4f93
